"""Initial relational schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('grants_verified', sa.Boolean(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.CheckConstraint('duration_hours >= 0', name=op.f('ck_activity_rule_0')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_activity_source'))
    )
    op.create_table('career_framework',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_career_framework_rule_0')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_framework')),
    sa.UniqueConstraint('source', 'name', name=op.f('uq_career_framework_source'))
    )
    op.create_table('catalog_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('catalog_version', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('catalog_version >= 1', name=op.f('ck_catalog_state_rule_0')),
    sa.CheckConstraint('policy_version >= 1', name=op.f('ck_catalog_state_rule_1')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_state')),
    sa.UniqueConstraint('name', name=op.f('uq_catalog_state_name'))
    )
    op.create_table('department',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('source', 'name', name=op.f('uq_department_source'))
    )
    op.create_table('import_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('digest', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_record')),
    sa.UniqueConstraint('source', 'kind', 'external_id', name=op.f('uq_import_record_source'))
    )
    op.create_table('skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_skill_source'))
    )
    op.create_table('activity_audience',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_audience_activity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_audience')),
    sa.UniqueConstraint('activity_id', 'role', 'grade', name=op.f('uq_activity_audience_activity_id'))
    )
    op.create_index(op.f('ix_activity_audience_activity_id'), 'activity_audience', ['activity_id'], unique=False)
    op.create_table('activity_prerequisite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.CheckConstraint('required_level BETWEEN 0 AND 5', name=op.f('ck_activity_prerequisite_rule_0')),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_prerequisite_activity_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_activity_prerequisite_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_prerequisite')),
    sa.UniqueConstraint('activity_id', 'skill_id', name=op.f('uq_activity_prerequisite_activity_id'))
    )
    op.create_index(op.f('ix_activity_prerequisite_activity_id'), 'activity_prerequisite', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_prerequisite_skill_id'), 'activity_prerequisite', ['skill_id'], unique=False)
    op.create_table('activity_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_session_activity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_session')),
    sa.UniqueConstraint('activity_id', 'starts_on', name=op.f('uq_activity_session_activity_id'))
    )
    op.create_index(op.f('ix_activity_session_activity_id'), 'activity_session', ['activity_id'], unique=False)
    op.create_table('activity_skill_effect',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('gain', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.CheckConstraint('gain >= 0', name=op.f('ck_activity_skill_effect_rule_0')),
    sa.CheckConstraint('max_level BETWEEN 0 AND 5', name=op.f('ck_activity_skill_effect_rule_1')),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_skill_effect_activity_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_activity_skill_effect_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_skill_effect')),
    sa.UniqueConstraint('activity_id', 'skill_id', name=op.f('uq_activity_skill_effect_activity_id'))
    )
    op.create_index(op.f('ix_activity_skill_effect_activity_id'), 'activity_skill_effect', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_skill_effect_skill_id'), 'activity_skill_effect', ['skill_id'], unique=False)
    op.create_table('career_track',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['career_framework.id'], name=op.f('fk_career_track_framework_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_track')),
    sa.UniqueConstraint('framework_id', 'name', name=op.f('uq_career_track_framework_id'))
    )
    op.create_index(op.f('ix_career_track_framework_id'), 'career_track', ['framework_id'], unique=False)
    op.create_table('grade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('audience_grade', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['career_framework.id'], name=op.f('fk_grade_framework_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade')),
    sa.UniqueConstraint('framework_id', 'name', name=op.f('uq_grade_framework_id'))
    )
    op.create_index(op.f('ix_grade_framework_id'), 'grade', ['framework_id'], unique=False)
    op.create_table('role_level',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_role_level_rule_0')),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], name=op.f('fk_role_level_grade_id')),
    sa.ForeignKeyConstraint(['track_id'], ['career_track.id'], name=op.f('fk_role_level_track_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_level')),
    sa.UniqueConstraint('track_id', 'grade_id', name=op.f('uq_role_level_track_id'))
    )
    op.create_index(op.f('ix_role_level_grade_id'), 'role_level', ['grade_id'], unique=False)
    op.create_index(op.f('ix_role_level_track_id'), 'role_level', ['track_id'], unique=False)
    op.create_table('career_transition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_level_id', sa.Uuid(), nullable=False),
    sa.Column('to_level_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['from_level_id'], ['role_level.id'], name=op.f('fk_career_transition_from_level_id')),
    sa.ForeignKeyConstraint(['to_level_id'], ['role_level.id'], name=op.f('fk_career_transition_to_level_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_transition')),
    sa.UniqueConstraint('from_level_id', 'to_level_id', name=op.f('uq_career_transition_from_level_id'))
    )
    op.create_index(op.f('ix_career_transition_from_level_id'), 'career_transition', ['from_level_id'], unique=False)
    op.create_index(op.f('ix_career_transition_to_level_id'), 'career_transition', ['to_level_id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('role_level_id', sa.Uuid(), nullable=False),
    sa.Column('last_review_date', sa.Date(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_language', sa.Text(), nullable=False),
    sa.Column('work_format', sa.Text(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('history_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('history_version >= 1', name=op.f('ck_employee_rule_1')),
    sa.CheckConstraint('profile_version >= 1', name=op.f('ck_employee_rule_0')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_employee_department_id')),
    sa.ForeignKeyConstraint(['manager_id'], ['employee.id'], name=op.f('fk_employee_manager_id')),
    sa.ForeignKeyConstraint(['role_level_id'], ['role_level.id'], name=op.f('fk_employee_role_level_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_employee_source'))
    )
    op.create_index(op.f('ix_employee_department_id'), 'employee', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_manager_id'), 'employee', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employee_role_level_id'), 'employee', ['role_level_id'], unique=False)
    op.create_table('role_skill_requirement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_level_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.CheckConstraint('required_level BETWEEN 0 AND 5', name=op.f('ck_role_skill_requirement_rule_0')),
    sa.ForeignKeyConstraint(['role_level_id'], ['role_level.id'], name=op.f('fk_role_skill_requirement_role_level_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_role_skill_requirement_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_skill_requirement')),
    sa.UniqueConstraint('role_level_id', 'skill_id', name=op.f('uq_role_skill_requirement_role_level_id'))
    )
    op.create_index(op.f('ix_role_skill_requirement_role_level_id'), 'role_skill_requirement', ['role_level_id'], unique=False)
    op.create_index(op.f('ix_role_skill_requirement_skill_id'), 'role_skill_requirement', ['skill_id'], unique=False)
    op.create_table('vacancy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('role_level_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('open','closed')", name=op.f('ck_vacancy_rule_0')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_vacancy_rule_1')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_vacancy_department_id')),
    sa.ForeignKeyConstraint(['role_level_id'], ['role_level.id'], name=op.f('fk_vacancy_role_level_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancy'))
    )
    op.create_index(op.f('ix_vacancy_department_id'), 'vacancy', ['department_id'], unique=False)
    op.create_index(op.f('ix_vacancy_role_level_id'), 'vacancy', ['role_level_id'], unique=False)
    op.create_table('employee_career_goal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('role_level_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_employee_career_goal_employee_id')),
    sa.ForeignKeyConstraint(['role_level_id'], ['role_level.id'], name=op.f('fk_employee_career_goal_role_level_id')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], name=op.f('fk_employee_career_goal_vacancy_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_career_goal')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_employee_career_goal_employee_id'))
    )
    op.create_index(op.f('ix_employee_career_goal_employee_id'), 'employee_career_goal', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_career_goal_role_level_id'), 'employee_career_goal', ['role_level_id'], unique=False)
    op.create_index(op.f('ix_employee_career_goal_vacancy_id'), 'employee_career_goal', ['vacancy_id'], unique=False)
    op.create_table('employee_skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('verified_level', sa.Integer(), nullable=False),
    sa.Column('claimed_level', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('assessed_on', sa.Date(), nullable=True),
    sa.CheckConstraint('claimed_level BETWEEN 0 AND 5', name=op.f('ck_employee_skill_rule_1')),
    sa.CheckConstraint('verified_level BETWEEN 0 AND 5', name=op.f('ck_employee_skill_rule_0')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_employee_skill_employee_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_employee_skill_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_skill')),
    sa.UniqueConstraint('employee_id', 'skill_id', name=op.f('uq_employee_skill_employee_id'))
    )
    op.create_index(op.f('ix_employee_skill_employee_id'), 'employee_skill', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skill_skill_id'), 'employee_skill', ['skill_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('participation_key', sa.Text(), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_enrollment_activity_id')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_enrollment_employee_id')),
    sa.ForeignKeyConstraint(['session_id'], ['activity_session.id'], name=op.f('fk_enrollment_session_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment')),
    sa.UniqueConstraint('employee_id', 'activity_id', 'participation_key', name=op.f('uq_enrollment_employee_id')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_enrollment_source'))
    )
    op.create_index(op.f('ix_enrollment_activity_id'), 'enrollment', ['activity_id'], unique=False)
    op.create_index(op.f('ix_enrollment_employee_id'), 'enrollment', ['employee_id'], unique=False)
    op.create_index(op.f('ix_enrollment_session_id'), 'enrollment', ['session_id'], unique=False)
    op.create_table('recommendation_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_recommendation_run_employee_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_run'))
    )
    op.create_index(op.f('ix_recommendation_run_employee_id'), 'recommendation_run', ['employee_id'], unique=False)
    op.create_table('skill_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('before_level', sa.Integer(), nullable=False),
    sa.Column('after_level', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('after_level BETWEEN 0 AND 5', name=op.f('ck_skill_change_rule_1')),
    sa.CheckConstraint('before_level BETWEEN 0 AND 5', name=op.f('ck_skill_change_rule_0')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_skill_change_employee_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_skill_change_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_change')),
    sa.UniqueConstraint('origin', 'origin_id', 'skill_id', name=op.f('uq_skill_change_origin'))
    )
    op.create_index(op.f('ix_skill_change_employee_id'), 'skill_change', ['employee_id'], unique=False)
    op.create_index(op.f('ix_skill_change_skill_id'), 'skill_change', ['skill_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('ui_mode', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('reduced_motion', sa.Boolean(), nullable=False),
    sa.CheckConstraint("locale IN ('ru','kk','en')", name=op.f('ck_user_rule_2')),
    sa.CheckConstraint("role IN ('employee','reviewer','hr','admin')", name=op.f('ck_user_rule_0')),
    sa.CheckConstraint("ui_mode IN ('classic','rpg')", name=op.f('ck_user_rule_1')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_user_employee_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_user_employee_id')),
    sa.UniqueConstraint('login', name=op.f('uq_user_login'))
    )
    op.create_index(op.f('ix_user_employee_id'), 'user', ['employee_id'], unique=False)
    op.create_table('vacancy_requirement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.CheckConstraint('required_level BETWEEN 0 AND 5', name=op.f('ck_vacancy_requirement_rule_0')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_vacancy_requirement_skill_id')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], name=op.f('fk_vacancy_requirement_vacancy_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancy_requirement')),
    sa.UniqueConstraint('vacancy_id', 'skill_id', name=op.f('uq_vacancy_requirement_vacancy_id'))
    )
    op.create_index(op.f('ix_vacancy_requirement_skill_id'), 'vacancy_requirement', ['skill_id'], unique=False)
    op.create_index(op.f('ix_vacancy_requirement_vacancy_id'), 'vacancy_requirement', ['vacancy_id'], unique=False)
    op.create_table('verification_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_id', sa.Uuid(), nullable=True),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_level', sa.Integer(), nullable=True),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('project_role', sa.Text(), nullable=True),
    sa.Column('contribution', sa.Text(), nullable=True),
    sa.CheckConstraint("(kind = 'skill' AND skill_id IS NOT NULL AND claimed_level IS NOT NULL) OR (kind = 'experience' AND start_date IS NOT NULL AND end_date >= start_date)", name=op.f('ck_verification_request_rule_2')),
    sa.CheckConstraint("kind IN ('skill','experience')", name=op.f('ck_verification_request_rule_1')),
    sa.CheckConstraint("status IN ('draft','submitted','in_review','approved','rejected','needs_changes')", name=op.f('ck_verification_request_rule_0')),
    sa.CheckConstraint('claimed_level BETWEEN 0 AND 5', name=op.f('ck_verification_request_rule_5')),
    sa.CheckConstraint('profile_version >= 1', name=op.f('ck_verification_request_rule_3')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_verification_request_rule_4')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_verification_request_employee_id')),
    sa.ForeignKeyConstraint(['previous_id'], ['verification_request.id'], name=op.f('fk_verification_request_previous_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_verification_request_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_request'))
    )
    op.create_index(op.f('ix_verification_request_employee_id'), 'verification_request', ['employee_id'], unique=False)
    op.create_index(op.f('ix_verification_request_previous_id'), 'verification_request', ['previous_id'], unique=False)
    op.create_index(op.f('ix_verification_request_skill_id'), 'verification_request', ['skill_id'], unique=False)
    op.create_table('activity_completion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_time_source', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], name=op.f('fk_activity_completion_confirmed_by')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], name=op.f('fk_activity_completion_enrollment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_completion')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_activity_completion_enrollment_id'))
    )
    op.create_index(op.f('ix_activity_completion_confirmed_by'), 'activity_completion', ['confirmed_by'], unique=False)
    op.create_index(op.f('ix_activity_completion_enrollment_id'), 'activity_completion', ['enrollment_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_audit_event_actor_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index(op.f('ix_audit_event_actor_id'), 'audit_event', ['actor_id'], unique=False)
    op.create_table('completion_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('submitted','confirmed')", name=op.f('ck_completion_request_rule_0')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], name=op.f('fk_completion_request_enrollment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_completion_request')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_completion_request_enrollment_id'))
    )
    op.create_index(op.f('ix_completion_request_enrollment_id'), 'completion_request', ['enrollment_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['verification_request.id'], name=op.f('fk_evidence_request_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_request_id'), 'evidence', ['request_id'], unique=False)
    op.create_table('experience_skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['verification_request.id'], name=op.f('fk_experience_skill_request_id')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_experience_skill_skill_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_skill')),
    sa.UniqueConstraint('request_id', 'skill_id', name=op.f('uq_experience_skill_request_id'))
    )
    op.create_index(op.f('ix_experience_skill_request_id'), 'experience_skill', ['request_id'], unique=False)
    op.create_index(op.f('ix_experience_skill_skill_id'), 'experience_skill', ['skill_id'], unique=False)
    op.create_table('idempotency_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_idempotency_record_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_record')),
    sa.UniqueConstraint('user_id', 'operation', 'key', name=op.f('uq_idempotency_record_user_id'))
    )
    op.create_index(op.f('ix_idempotency_record_user_id'), 'idempotency_record', ['user_id'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('digest', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_import_batch_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch')),
    sa.UniqueConstraint('source', 'digest', name=op.f('uq_import_batch_source'))
    )
    op.create_index(op.f('ix_import_batch_created_by'), 'import_batch', ['created_by'], unique=False)
    op.create_table('permission_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_permission_grant_department_id')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_permission_grant_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_grant')),
    sa.UniqueConstraint('user_id', 'department_id', 'permission', 'scope', name=op.f('uq_permission_grant_user_id'))
    )
    op.create_index(op.f('ix_permission_grant_department_id'), 'permission_grant', ['department_id'], unique=False)
    op.create_index(op.f('ix_permission_grant_user_id'), 'permission_grant', ['user_id'], unique=False)
    op.create_table('promotion_review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('role_level_id', sa.Uuid(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('requirements_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('submitted','approved','rejected')", name=op.f('ck_promotion_review_rule_0')),
    sa.CheckConstraint('profile_version >= 1', name=op.f('ck_promotion_review_rule_1')),
    sa.CheckConstraint('requirements_version >= 1', name=op.f('ck_promotion_review_rule_2')),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], name=op.f('fk_promotion_review_decided_by')),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_promotion_review_employee_id')),
    sa.ForeignKeyConstraint(['role_level_id'], ['role_level.id'], name=op.f('fk_promotion_review_role_level_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_review'))
    )
    op.create_index(op.f('ix_promotion_review_decided_by'), 'promotion_review', ['decided_by'], unique=False)
    op.create_index(op.f('ix_promotion_review_employee_id'), 'promotion_review', ['employee_id'], unique=False)
    op.create_index(op.f('ix_promotion_review_role_level_id'), 'promotion_review', ['role_level_id'], unique=False)
    op.create_table('recommendation_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_recommendation_item_activity_id')),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_run.id'], name=op.f('fk_recommendation_item_run_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_item')),
    sa.UniqueConstraint('run_id', 'activity_id', name=op.f('uq_recommendation_item_run_id')),
    sa.UniqueConstraint('run_id', 'position', name='uq_run_position')
    )
    op.create_index(op.f('ix_recommendation_item_activity_id'), 'recommendation_item', ['activity_id'], unique=False)
    op.create_index(op.f('ix_recommendation_item_run_id'), 'recommendation_item', ['run_id'], unique=False)
    op.create_table('reviewer_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], name=op.f('fk_reviewer_assignment_assigned_by')),
    sa.ForeignKeyConstraint(['request_id'], ['verification_request.id'], name=op.f('fk_reviewer_assignment_request_id')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('fk_reviewer_assignment_reviewer_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviewer_assignment')),
    sa.UniqueConstraint('request_id', name=op.f('uq_reviewer_assignment_request_id'))
    )
    op.create_index(op.f('ix_reviewer_assignment_assigned_by'), 'reviewer_assignment', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_reviewer_assignment_request_id'), 'reviewer_assignment', ['request_id'], unique=False)
    op.create_index(op.f('ix_reviewer_assignment_reviewer_id'), 'reviewer_assignment', ['reviewer_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_session_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_session_token_hash'))
    )
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('verification_review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rubric', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_level', sa.Integer(), nullable=True),
    sa.CheckConstraint("decision IN ('approved','rejected','needs_changes')", name=op.f('ck_verification_review_rule_0')),
    sa.CheckConstraint('observed_level BETWEEN 0 AND 5', name=op.f('ck_verification_review_rule_1')),
    sa.ForeignKeyConstraint(['request_id'], ['verification_request.id'], name=op.f('fk_verification_review_request_id')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('fk_verification_review_reviewer_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_review')),
    sa.UniqueConstraint('request_id', name=op.f('uq_verification_review_request_id'))
    )
    op.create_index(op.f('ix_verification_review_request_id'), 'verification_review', ['request_id'], unique=False)
    op.create_index(op.f('ix_verification_review_reviewer_id'), 'verification_review', ['reviewer_id'], unique=False)
    op.create_table('import_issue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_import_issue_batch_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_issue'))
    )
    op.create_index(op.f('ix_import_issue_batch_id'), 'import_issue', ['batch_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_issue_batch_id'), table_name='import_issue')
    op.drop_table('import_issue')
    op.drop_index(op.f('ix_verification_review_reviewer_id'), table_name='verification_review')
    op.drop_index(op.f('ix_verification_review_request_id'), table_name='verification_review')
    op.drop_table('verification_review')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_reviewer_assignment_reviewer_id'), table_name='reviewer_assignment')
    op.drop_index(op.f('ix_reviewer_assignment_request_id'), table_name='reviewer_assignment')
    op.drop_index(op.f('ix_reviewer_assignment_assigned_by'), table_name='reviewer_assignment')
    op.drop_table('reviewer_assignment')
    op.drop_index(op.f('ix_recommendation_item_run_id'), table_name='recommendation_item')
    op.drop_index(op.f('ix_recommendation_item_activity_id'), table_name='recommendation_item')
    op.drop_table('recommendation_item')
    op.drop_index(op.f('ix_promotion_review_role_level_id'), table_name='promotion_review')
    op.drop_index(op.f('ix_promotion_review_employee_id'), table_name='promotion_review')
    op.drop_index(op.f('ix_promotion_review_decided_by'), table_name='promotion_review')
    op.drop_table('promotion_review')
    op.drop_index(op.f('ix_permission_grant_user_id'), table_name='permission_grant')
    op.drop_index(op.f('ix_permission_grant_department_id'), table_name='permission_grant')
    op.drop_table('permission_grant')
    op.drop_index(op.f('ix_import_batch_created_by'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_idempotency_record_user_id'), table_name='idempotency_record')
    op.drop_table('idempotency_record')
    op.drop_index(op.f('ix_experience_skill_skill_id'), table_name='experience_skill')
    op.drop_index(op.f('ix_experience_skill_request_id'), table_name='experience_skill')
    op.drop_table('experience_skill')
    op.drop_index(op.f('ix_evidence_request_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_completion_request_enrollment_id'), table_name='completion_request')
    op.drop_table('completion_request')
    op.drop_index(op.f('ix_audit_event_actor_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_activity_completion_enrollment_id'), table_name='activity_completion')
    op.drop_index(op.f('ix_activity_completion_confirmed_by'), table_name='activity_completion')
    op.drop_table('activity_completion')
    op.drop_index(op.f('ix_verification_request_skill_id'), table_name='verification_request')
    op.drop_index(op.f('ix_verification_request_previous_id'), table_name='verification_request')
    op.drop_index(op.f('ix_verification_request_employee_id'), table_name='verification_request')
    op.drop_table('verification_request')
    op.drop_index(op.f('ix_vacancy_requirement_vacancy_id'), table_name='vacancy_requirement')
    op.drop_index(op.f('ix_vacancy_requirement_skill_id'), table_name='vacancy_requirement')
    op.drop_table('vacancy_requirement')
    op.drop_index(op.f('ix_user_employee_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_skill_change_skill_id'), table_name='skill_change')
    op.drop_index(op.f('ix_skill_change_employee_id'), table_name='skill_change')
    op.drop_table('skill_change')
    op.drop_index(op.f('ix_recommendation_run_employee_id'), table_name='recommendation_run')
    op.drop_table('recommendation_run')
    op.drop_index(op.f('ix_enrollment_session_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_employee_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_activity_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_employee_skill_skill_id'), table_name='employee_skill')
    op.drop_index(op.f('ix_employee_skill_employee_id'), table_name='employee_skill')
    op.drop_table('employee_skill')
    op.drop_index(op.f('ix_employee_career_goal_vacancy_id'), table_name='employee_career_goal')
    op.drop_index(op.f('ix_employee_career_goal_role_level_id'), table_name='employee_career_goal')
    op.drop_index(op.f('ix_employee_career_goal_employee_id'), table_name='employee_career_goal')
    op.drop_table('employee_career_goal')
    op.drop_index(op.f('ix_vacancy_role_level_id'), table_name='vacancy')
    op.drop_index(op.f('ix_vacancy_department_id'), table_name='vacancy')
    op.drop_table('vacancy')
    op.drop_index(op.f('ix_role_skill_requirement_skill_id'), table_name='role_skill_requirement')
    op.drop_index(op.f('ix_role_skill_requirement_role_level_id'), table_name='role_skill_requirement')
    op.drop_table('role_skill_requirement')
    op.drop_index(op.f('ix_employee_role_level_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_manager_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_department_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_career_transition_to_level_id'), table_name='career_transition')
    op.drop_index(op.f('ix_career_transition_from_level_id'), table_name='career_transition')
    op.drop_table('career_transition')
    op.drop_index(op.f('ix_role_level_track_id'), table_name='role_level')
    op.drop_index(op.f('ix_role_level_grade_id'), table_name='role_level')
    op.drop_table('role_level')
    op.drop_index(op.f('ix_grade_framework_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_career_track_framework_id'), table_name='career_track')
    op.drop_table('career_track')
    op.drop_index(op.f('ix_activity_skill_effect_skill_id'), table_name='activity_skill_effect')
    op.drop_index(op.f('ix_activity_skill_effect_activity_id'), table_name='activity_skill_effect')
    op.drop_table('activity_skill_effect')
    op.drop_index(op.f('ix_activity_session_activity_id'), table_name='activity_session')
    op.drop_table('activity_session')
    op.drop_index(op.f('ix_activity_prerequisite_skill_id'), table_name='activity_prerequisite')
    op.drop_index(op.f('ix_activity_prerequisite_activity_id'), table_name='activity_prerequisite')
    op.drop_table('activity_prerequisite')
    op.drop_index(op.f('ix_activity_audience_activity_id'), table_name='activity_audience')
    op.drop_table('activity_audience')
    op.drop_table('skill')
    op.drop_table('import_record')
    op.drop_table('department')
    op.drop_table('catalog_state')
    op.drop_table('career_framework')
    op.drop_table('activity')
    # ### end Alembic commands ###
